
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author LENOVO
 */
public class FrmMenu extends javax.swing.JFrame {
    
    public static  JDesktopPane jDesktopPane_menu;
    public static InterGestionarCategoria interGestionarCategoria;

   
    public FrmMenu() {
        initComponents();
        this.getSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        this.setTitle("Sistema de ventas");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho,(alto - 110));
        this.add(jDesktopPane_menu);
        interGestionarCategoria = new InterGestionarCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_Nuevo_Usuario = new javax.swing.JMenuItem();
        MenuItem_Gestionar_Usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItem_Nuevo_Producto = new javax.swing.JMenuItem();
        MenuItem_Gestionar_Productos = new javax.swing.JMenuItem();
        MenuItem_Actualizar_Stock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItem_Nuevo_Cliente = new javax.swing.JMenuItem();
        MenuItem_Gestionar_Clientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItem_Nueva_Categoria = new javax.swing.JMenuItem();
        MenuItem_Gestionar_Categorias = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItem_Nueva_Venta = new javax.swing.JMenuItem();
        MenuItem_Gestionar_Ventas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItem_Reportes_Clientes = new javax.swing.JMenuItem();
        MenuItem_Reportes_Categorias = new javax.swing.JMenuItem();
        MenuItem_Reportes_Productos = new javax.swing.JMenuItem();
        MenuItem_Reportes_Ventas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        MenuItem_Ver_Historial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        MenuItem_Cerrar_Sesion = new javax.swing.JMenuItem();

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Nuevo_Usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Nuevo_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        MenuItem_Nuevo_Usuario.setText("Nuevo Usuario");
        MenuItem_Nuevo_Usuario.setPreferredSize(new java.awt.Dimension(180, 30));
        MenuItem_Nuevo_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Nuevo_UsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Nuevo_Usuario);

        MenuItem_Gestionar_Usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Gestionar_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        MenuItem_Gestionar_Usuario.setText("Gestionar Usuario");
        MenuItem_Gestionar_Usuario.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu1.add(MenuItem_Gestionar_Usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Nuevo_Producto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Nuevo_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        MenuItem_Nuevo_Producto.setText("Nuevo Producto");
        MenuItem_Nuevo_Producto.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuItem_Nuevo_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Nuevo_ProductoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_Nuevo_Producto);

        MenuItem_Gestionar_Productos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Gestionar_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        MenuItem_Gestionar_Productos.setText("Gestionar Productos");
        MenuItem_Gestionar_Productos.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuItem_Gestionar_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Gestionar_ProductosActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItem_Gestionar_Productos);

        MenuItem_Actualizar_Stock.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Actualizar_Stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        MenuItem_Actualizar_Stock.setText("Actualizar Stock");
        MenuItem_Actualizar_Stock.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu2.add(MenuItem_Actualizar_Stock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Nuevo_Cliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Nuevo_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        MenuItem_Nuevo_Cliente.setText("Nuevo Cliente");
        MenuItem_Nuevo_Cliente.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(MenuItem_Nuevo_Cliente);

        MenuItem_Gestionar_Clientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Gestionar_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        MenuItem_Gestionar_Clientes.setText("Gestionar Clientes");
        MenuItem_Gestionar_Clientes.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(MenuItem_Gestionar_Clientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Nueva_Categoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Nueva_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        MenuItem_Nueva_Categoria.setText("Nueva Categoria");
        MenuItem_Nueva_Categoria.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuItem_Nueva_Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Nueva_CategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItem_Nueva_Categoria);

        MenuItem_Gestionar_Categorias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Gestionar_Categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        MenuItem_Gestionar_Categorias.setText("Gestionar Categorias");
        MenuItem_Gestionar_Categorias.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuItem_Gestionar_Categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Gestionar_CategoriasActionPerformed(evt);
            }
        });
        jMenu4.add(MenuItem_Gestionar_Categorias);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu5.setText("Facturar");
        jMenu5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Nueva_Venta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Nueva_Venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        MenuItem_Nueva_Venta.setText("Nueva Venta");
        MenuItem_Nueva_Venta.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(MenuItem_Nueva_Venta);

        MenuItem_Gestionar_Ventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Gestionar_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        MenuItem_Gestionar_Ventas.setText("Gestionar Ventas");
        MenuItem_Gestionar_Ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu5.add(MenuItem_Gestionar_Ventas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportes.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Reportes_Clientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Reportes_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        MenuItem_Reportes_Clientes.setText("Reportes Clientes");
        MenuItem_Reportes_Clientes.setPreferredSize(new java.awt.Dimension(200, 30));
        MenuItem_Reportes_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_Reportes_ClientesActionPerformed(evt);
            }
        });
        jMenu6.add(MenuItem_Reportes_Clientes);

        MenuItem_Reportes_Categorias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Reportes_Categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        MenuItem_Reportes_Categorias.setText("Reportes Categorias");
        MenuItem_Reportes_Categorias.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(MenuItem_Reportes_Categorias);

        MenuItem_Reportes_Productos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Reportes_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        MenuItem_Reportes_Productos.setText("Reportes Productos");
        MenuItem_Reportes_Productos.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(MenuItem_Reportes_Productos);

        MenuItem_Reportes_Ventas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Reportes_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        MenuItem_Reportes_Ventas.setText("Reportes Ventas");
        MenuItem_Reportes_Ventas.setPreferredSize(new java.awt.Dimension(200, 30));
        jMenu6.add(MenuItem_Reportes_Ventas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Ver_Historial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Ver_Historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        MenuItem_Ver_Historial.setText("Ver Historial");
        MenuItem_Ver_Historial.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu7.add(MenuItem_Ver_Historial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesion");
        jMenu8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        MenuItem_Cerrar_Sesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        MenuItem_Cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        MenuItem_Cerrar_Sesion.setText("Cerrar Sesion");
        MenuItem_Cerrar_Sesion.setPreferredSize(new java.awt.Dimension(150, 30));
        jMenu8.add(MenuItem_Cerrar_Sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_Nuevo_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Nuevo_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_Nuevo_UsuarioActionPerformed

    private void MenuItem_Reportes_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Reportes_ClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItem_Reportes_ClientesActionPerformed

    private void MenuItem_Nueva_CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Nueva_CategoriaActionPerformed
       InterCategoria interCategoria= new InterCategoria();
       jDesktopPane_menu.add(interCategoria);
       interCategoria.setVisible(true);
    }//GEN-LAST:event_MenuItem_Nueva_CategoriaActionPerformed

    private void MenuItem_Gestionar_CategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Gestionar_CategoriasActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_MenuItem_Gestionar_CategoriasActionPerformed

    private void MenuItem_Gestionar_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Gestionar_ProductosActionPerformed
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);
    }//GEN-LAST:event_MenuItem_Gestionar_ProductosActionPerformed

    private void MenuItem_Nuevo_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_Nuevo_ProductoActionPerformed
   InterProducto interProducto = new InterProducto();
        jDesktopPane_menu.add(interProducto);
        interProducto.setVisible(true);
    }//GEN-LAST:event_MenuItem_Nuevo_ProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_Actualizar_Stock;
    private javax.swing.JMenuItem MenuItem_Cerrar_Sesion;
    private javax.swing.JMenuItem MenuItem_Gestionar_Categorias;
    private javax.swing.JMenuItem MenuItem_Gestionar_Clientes;
    private javax.swing.JMenuItem MenuItem_Gestionar_Productos;
    private javax.swing.JMenuItem MenuItem_Gestionar_Usuario;
    private javax.swing.JMenuItem MenuItem_Gestionar_Ventas;
    private javax.swing.JMenuItem MenuItem_Nueva_Categoria;
    private javax.swing.JMenuItem MenuItem_Nueva_Venta;
    private javax.swing.JMenuItem MenuItem_Nuevo_Cliente;
    private javax.swing.JMenuItem MenuItem_Nuevo_Producto;
    private javax.swing.JMenuItem MenuItem_Nuevo_Usuario;
    private javax.swing.JMenuItem MenuItem_Reportes_Categorias;
    private javax.swing.JMenuItem MenuItem_Reportes_Clientes;
    private javax.swing.JMenuItem MenuItem_Reportes_Productos;
    private javax.swing.JMenuItem MenuItem_Reportes_Ventas;
    private javax.swing.JMenuItem MenuItem_Ver_Historial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem12;
    // End of variables declaration//GEN-END:variables
}
